# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNAV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_value', models.DecimalField(decimal_places=5, max_digits=25)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HoldingInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('purchase_NAV', models.DecimalField(decimal_places=5, max_digits=25)),
                ('number_of_units', models.DecimalField(decimal_places=5, max_digits=25)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amc', models.CharField(max_length=200)),
                ('scheme_name', models.CharField(max_length=200)),
                ('scheme_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SoldInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_date', models.DateField()),
                ('purchase_NAV', models.DecimalField(decimal_places=5, max_digits=25)),
                ('number_of_units', models.DecimalField(decimal_places=5, max_digits=25)),
                ('scheme_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investapp.Scheme')),
            ],
        ),
        migrations.CreateModel(
            name='TotalInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investapp.Scheme')),
            ],
        ),
        migrations.AddField(
            model_name='holdinginvestment',
            name='scheme_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investapp.Scheme'),
        ),
        migrations.AddField(
            model_name='dailynav',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investapp.Scheme'),
        ),
    ]
