# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holdinginvestment',
            old_name='scheme_code',
            new_name='scheme',
        ),
        migrations.RenameField(
            model_name='soldinvestment',
            old_name='scheme_code',
            new_name='scheme',
        ),
    ]
