# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investapp', '0002_auto_20180202_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheme',
            options={'ordering': ['scheme_name']},
        ),
        migrations.AddField(
            model_name='totalinvestment',
            name='latest_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
            preserve_default=False,
        ),
    ]
