# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investapp', '0003_auto_20180209_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalinvestment',
            old_name='latest_value',
            new_name='latest_val',
        ),
    ]
