# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investapp', '0004_auto_20180209_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalinvestment',
            name='latest_val',
        ),
    ]
